# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "apopa/bionic64"
  config.vm.hostname = "bionic64"
  config.vm.network "public_network", ip: "192.168.178.60"
  config.vm.provider :vmware_desktop do |vmware|
    vmware.allowlist_verified = true
    vmware.vmx["ethernet0.pcislotnumber"] = "33"
    vmware.memory = "512"
    vmware.cpus = "2"
  end
end